services:
  main:
    container_name: nestjs-main
    image: liutsing/delos-main:latest
    # build:
    #   context: .
    #   dockerfile: 'Dockerfile'
    ports:
      - 3001:3000
    restart: always
    networks:
      - maple-network
    environment:
      - MINIO_SERVICE=nestjs-minio
  minio:
    container_name: nestjs-minio
    image: liutsing/delos-minio:latest
    environment:
      - MINIO_ACCESS_KEY=XpiUE5sGLAXt4EtKgKiH
      - MINIO_SECRET_KEY=8qnIB6KhE5n5hxpxePeDewWpD47XLTs4K9CsUKKk
      - MINIO_I18N_BUCKET=i18n
    # build:
    #   context: .
    #   dockerfile: 'Dockerfile'
    # ports:
    #   - 8801:8801
    restart: always
    networks:
      - maple-network
networks:
  maple-network:
    name: maple-network
    external: true
