version: '2'

networks:
  maple-network:
    external:
      name: maple-network
services:
  main:
    container_name: nestjs-main
    build:
      context: ./packages/main
      dockerfile: 'Dockerfile'
    ports:
      - 3001:3000
    restart: always
    networks:
      - maple-network
    environment:
      - MINIO_SERVICE=nestjs-minio
  minio:
    container_name: nestjs-minio
    build:
      context: ./packages/minio
      dockerfile: 'Dockerfile'
    # ports:
    #   - 8801:8801
    restart: always
    networks:
      - maple-network
