version: '3.2'
services:
  maple-delos:
    build:
      context: .
      dockerfile: 'Dockerfile'
    # link:
    #   - "maple-mysql"
    #   - "maple-mongodb"
    #   - "maple-redis"
    ports:
      - '3001:3090'
networks:
  external:
    name: maple-network