services:
  main:
    container_name: maple-gateway
    image: liutsing/delos-main:latest
    ports:
      - 3001:3000
    restart: always
    networks:
      - maple-network
    environment:
      - MINIO_SERVICE=nestjs-minio
  minio:
    container_name: nestjs-minio
    image: liutsing/delos-minio:latest
    environment:
      - MINIO_ACCESS_KEY=363wbyRsqOAsWXt7jsWB
      - MINIO_SECRET_KEY=sUjdiu0xgCiGwwdFCsrG4YDR1u1xepC7KxjQqgZg
      - MINIO_I18N_BUCKET=i18n
    restart: always
    networks:
      - maple-network
networks:
  maple-network:
    name: maple-network
    external: true
