services:
  main:
    container_name: maple-gateway
    image: liutsing/delos-main:${VERSION}
    ports:
      - 4001:3000
    restart: always
    networks:
      - maple-network
    environment:
      - MINIO_SERVICE=nestjs-minio
      - VERSION=${VERSION}
  minio:
    container_name: nestjs-minio
    image: liutsing/delos-minio:${VERSION}
    environment:
      # PC
      #   - MINIO_ACCESS_KEY=ve1GAYxfTzNLkDwCRQCs
      #   - MINIO_SECRET_KEY=2RYflyXUCQf6BTQnxwAbRz1sjmLIqHlDEjvjxss9
      # mac
      - MINIO_ACCESS_KEY=363wbyRsqOAsWXt7jsWB
      - MINIO_SECRET_KEY=sUjdiu0xgCiGwwdFCsrG4YDR1u1xepC7KxjQqgZg
      - MINIO_I18N_BUCKET=i18n
      - VERSION=${VERSION}
    restart: always
    networks:
      - maple-network
networks:
  maple-network:
    name: maple-network
    external: true
