services:
  main:
    container_name: maple-gateway
    image: liutsing/delos-main:${VERSION}
    ports:
      - 4001:3000
    restart: always
    networks:
      - maple-network
    environment:
      - MINIO_SERVICE=nestjs-minio
      - VERSION=${VERSION}
      - RABBITMQ_URL=amqp://user:bitnami@rabbitmq-server:5672/
      - PUPPETEER_SERVICE=maple-puppeteer
  minio:
    container_name: nestjs-minio
    image: liutsing/delos-minio:${VERSION}
    environment:
      - MINIO_I18N_BUCKET=i18n-bucket
      - VERSION=${VERSION}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    restart: always
    networks:
      - maple-network
  puppeteer:
    container_name: maple-puppeteer
    image: liutsing/service-puppeteer:${VERSION}
    restart: always
    networks:
      - maple-network
networks:
  maple-network:
    name: maple-network
    external: true
