version: '2'

networks:
  maple-network:
    external:
      name: maple-network
services:
  maple-delos:
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - 3001:3000
    networks:
      - maple-network
