version: '2'

networks:
  maple-network:
    external:
      name: maple-network
services:
  maple-minio-microservice:
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - 8801:8801
    restart: always
    networks:
      - maple-network
